name: CI

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - 3dldf
          - 8sync
          - a2ps
          - acct
          - acm
          - adns
          - alive
          - anubis
          - apl
          - archimedes
          - aris
          - artanis
          - aspell
          - auctex
          - autoconf
          - autoconf-archive
          - autogen
          - automake
          - avl
          - ballandpaddle
          - barcode
          - bash
          - bayonne
          - bazaar
          - bc
          - behistun
          - bfd
          - binutils
          - bison
          - bool
          - bpel2owfn
          - c-graph
          - ccaudio
          - ccd2cue
          - ccide
          - ccrtp
          - ccscript
          - cflow
          - cgicc
          - chess
          - cim
          - classpath
          - classpathx
          - clisp
          - combine
          - commoncpp
          - complexity
          - config
          - consensus
          - coreutils
          - cpio
          - cppi
          - cssc
          - cursynth
          - dap
          - datamash
          - dc
          - ddd
          - ddrescue
          - dejagnu
          - denemo
          - dia
          - dico
          - diction
          - diffutils
          - direvent
          - djgpp
          - dominion
          - dr-geo
          - easejs
          - ed
          - edma
          - electric
          - emacs
          - emacs-muse
          - emms
          - enscript
          - epsilon
          - fdisk
          - ferret
          - findutils
          - fisicalab
          - foliot
          - fontopia
          - fontutils
          - freedink
          - freefont
          - freeipmi
          - freetalk
          - fribidi
          - g-golf
          - gama
          - garpd
          - gawk
          - gcal
          - gcc
          - gcide
          - gcl
          - gcompris
          - gdb
          - gdbm
          - gengen
          - gengetopt
          - gettext
          - gforth
          - ggradebook
          - ghostscript
          - gift
          - gimp
          - glean
          - global
          - glpk
          - glue
          - gmediaserver
          - gmp
          - gnash
          - gnat
          - gnats
          - gnatsweb
          - gnowsys
          - gnu-c-manual
          - gnu-crypto
          - gnu-pw-mgr
          - gnuae
          - gnuastro
          - gnubatch
          - gnubg
          - gnubiff
          - gnubik
          - gnucap
          - gnucash
          - gnucobol
          - gnucomm
          - gnudos
          - gnufm
          - gnugo
          - gnuit
          - gnujdoc
          - gnujump
          - gnukart
          - gnulib
          - gnumach
          - gnumed
          - gnumeric
          - gnump3d
          - gnun
          - gnunet
          - gnupg
          - gnupod
          - gnuprologjava
          - gnuradio
          - gnurobots
          - gnuschool
          - gnushogi
          - gnusound
          - gnuspeech
          - gnuspool
          - gnustandards
          - gnustep
          - gnutls
          - gnutrition
          - gnuzilla
          - goptical
          - gorm
          - gpaint
          - gperf
          - gprolog
          - grabcomics
          - greg
          - grep
          - gretl
          - groff
          - grub
          - gsasl
          - gsegrafix
          - gsl
          - gslip
          - gsrc
          - gss
          - gtick
          - gtypist
          - guile
          - guile-cv
          - guile-dbi
          - guile-gnome
          - guile-ncurses
          - guile-opengl
          - guile-rpc
          - guile-sdl
          - guix
          - gurgle
          - gv
          - gvpe
          - gwl
          - gxmessage
          - gzip
          - halifax
          - health
          - hello
          - help2man
          - hp2xx
          - html-info
          - httptunnel
          - hurd
          - hyperbole
          - icecat
          - idutils
          - ignuit
          - indent
          - inetutils
          - inklingreader
          - intlfonts
          - jacal
          - jami
          - java-getopt
          - jel
          - jitter
          - jtw
          - jwhois
          - kawa
          - kopi
          - leg
          - less
          - libc
          - libcdio
          - libdbh
          - liberty-eiffel
          - libextractor
          - libffcall
          - libgcrypt
          - libiconv
          - libidn
          - libjit
          - libmatheval
          - libmicrohttpd
          - libredwg
          - librejs
          - libsigsegv
          - libtasn1
          - libtool
          - libunistring
          - libxmi
          - lightning
          - lilypond
          - lims
          - linux-libre
          - liquidwar6
          - lispintro
          - lrzsz
          - lsh
          - m4
          - macchanger
          - mailman
          - mailutils
          - make
          - marst
          - maverik
          - mc
          - mcron
          - mcsim
          - mdk
          - mediagoblin
          - melting
          - mempool
          - mes
          - metaexchange
          - metahtml
          - metalogic-inference
          - mifluz
          - mig
          - miscfiles
          - mit-scheme
          - moe
          - motti
          - mpc
          - mpfr
          - mpria
          - mtools
          - nana
          - nano
          - nano-archimedes
          - ncurses
          - nettle
          - network
          - ocrad
          - octave
          - oleo
          - oo-browser
          - orgadoc
          - osip
          - panorama
          - parallel
          - parted
          - pascal
          - patch
          - paxutils
          - pcb
          - pem
          - pexec
          - pies
          - pipo
          - plotutils
          - poke
          - polyxmass
          - powerguru
          - proxyknife
          - pspp
          - psychosynth
          - pth
          - pythonwebkit
          - qexo
          - quickthreads
          - r
          - radius
          - rcs
          - readline
          - recutils
          - reftex
          - remotecontrol
          - rottlog
          - rpge
          - rush
          - sather
          - scm
          - screen
          - sed
          - serveez
          - sharutils
          - shepherd
          - shishi
          - shmm
          - shtool
          - sipwitch
          - slib
          - smalltalk
          - social
          - solfege
          - spacechart
          - spell
          - sqltutor
          - src-highlite
          - ssw
          - stalkerfs
          - stow
          - stump
          - superopt
          - swbis
          - sysutils
          - taler
          - talkfilters
          - tar
          - termcap
          - termutils
          - teseq
          - teximpatient
          - texinfo
          - texmacs
          - time
          - tramp
          - trans-coord
          - trueprint
          - unifont
          - units
          - unrtf
          - userv
          - uucp
          - vc-dwim
          - vcdimager
          - vera
          - vmgen
          - wb
          - wdiff
          - websocket4j
          - webstump
          - wget
          - which
          - womb
          - xaos
          - xboard
          - xlogmaster
          - xmlat
          - xnee
          - xorriso
          - zile

    steps:
      # debug info about this machine
      - run: uname -a
      - run: free
      - run: env
      - run: mount
      - run: lscpu
      - run: lsmem
      - run: lsblk
      - run: lspci
      - run: lsipc
      - run: whoami

      # Get the code
      - uses: actions/checkout@v2
      - run: git fetch --all --tags
      - run: top -b -n 1 | head -n5

      # Zig
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: "0.10.0"
      - run: zig version
      - run: zig cc --version
      - run: zig env

      - uses: nektro/actions-setup-zigmod@v1
      - run: zigmod version
      - run: zigmod ci
      - run: zig build

      # Actual GNU project to test building
      - run: git clone https://git.savannah.gnu.org/git/{{ matrix.project }}.git
      - run: |
          cd {{ matrix.project }}
          mkdir out
          chmod +x ./bootstrap && ./bootstrap
          ./configure
          make install DESTDIR=out
          ls out
