name: CI

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        project:
          - alive
          - apl
          - autoconf
          - autogen
          - automake
          - barcode
          - bash
          - bc
          - binutils
          - bison
          - chess
          - clisp
          - coreutils
          - cpio
          - ddrescue
          - diffutils
          - direvent
          - ed
          - emacs
          - fdisk
          - findutils
          - fontutils
          - gawk
          - gcc
          - gdb
          - gettext
          - gforth
          - gift
          - gimp
          - gmp
          - gorm
          - gpaint
          - gperf
          - grep
          - grub
          - guile
          - gzip
          - hello
          - icecat
          - idutils
          - inetutils
          - m4
          - mailutils
          - make
          - mes
          - mtools
          - nano
          - parallel
          - parted
          - pascal
          - patch
          - paxutils
          - plotutils
          - r
          - recutils
          - screen
          - sed
          - sharutils
          - smalltalk
          - sysutils
          - tar
          - termutils
          - texinfo
          - time
          - wget
          - which

    steps:
      # debug info about this machine
      - run: uname -a
      - run: free
      - run: env
      - run: mount
      - run: lscpu
      - run: lsmem
      - run: lsblk
      - run: lspci
      - run: lsipc
      - run: whoami

      # Get the code
      - uses: actions/checkout@v2
      - run: git fetch --all --tags
      - run: top -b -n 1 | head -n5

      # Zig
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: "0.10.0"
      - run: zig version
      - run: zig cc --version
      - run: zig env

      - uses: nektro/actions-setup-zigmod@v1
      - run: zigmod version
      - run: zigmod ci
      - run: zig build

      # Actual GNU project to test building
      - run: |
          PROJECT={{ matrix.project }}
          git clone https://git.savannah.gnu.org/git/${PROJECT}.git
      - run: |
          cd {{ matrix.project }}
          mkdir out
          chmod +x ./bootstrap && ./bootstrap
          ./configure
          make install DESTDIR=out
          ls out
